//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.OgrenciRezervasyonİliskisi = new HashSet<OgrenciRezervasyonİliskisi>();
            this.OgrenciSecilenMalzemeVeZamani = new HashSet<OgrenciSecilenMalzemeVeZamani>();
            this.OgrenciCalismaTuru = new HashSet<OgrenciCalismaTuru>();
            this.Dersler = new HashSet<Dersler>();
        }
    
        public int kullanıcı_id { get; set; }
        public string kullanıcı_adi { get; set; }
        public string kullanıcı_soyadi { get; set; }
        public string kullanıcı_bolumu { get; set; }
        public int kullanıcı_danisman_id { get; set; }
        public string kullanıcı_sifre { get; set; }
    
        public virtual Danisman Danisman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciRezervasyonİliskisi> OgrenciRezervasyonİliskisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciSecilenMalzemeVeZamani> OgrenciSecilenMalzemeVeZamani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciCalismaTuru> OgrenciCalismaTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dersler> Dersler { get; set; }
    }
}
