//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageBorrowDate
    {
        public int storage_borrow_id { get; set; }
        public int storage_student_id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual StudentStorage StudentStorage { get; set; }
    }
}
