//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StorageBorrowDates = new HashSet<StorageBorrowDate>();
            this.StudentStorages = new HashSet<StudentStorage>();
        }
    
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string student_surname { get; set; }
        public short student_department_id { get; set; }
        public int student_rez_id { get; set; }
        public int student_store_id { get; set; }
        public int student_lecturer_id { get; set; }
        public System.DateTime student_store_startdate { get; set; }
        public System.DateTime student_store_enddate { get; set; }
        public string student_tel { get; set; }
        public int student_worktype_id { get; set; }
        public int student_course_id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Rezervation Rezervation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageBorrowDate> StorageBorrowDates { get; set; }
        public virtual StudentStorage StudentStorage { get; set; }
        public virtual WorkType WorkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentStorage> StudentStorages { get; set; }
    }
}
